export const products = {
    // Pizze
    pizze: [
    {   id: 1, 
        name: "Margherita", 
        description: "Pizza classica con pomodoro e mozzarella", 
        ingredients: ["Pomodoro", "Mozzarella", "Basilico"], 
        image: "margherita.jpg", 
        category: "Pizze", 
        price: 5.00 
    },
    {   id: 2, 
        name: "Diavola", 
        description: "Pizza con salame piccante", 
        ingredients: ["Pomodoro", "Mozzarella", "Salame piccante"], 
        image: "diavola.jpg", 
        category: "Pizze", 
        price: 6.50 
    },
    {   id: 3, 
        name: "Quattro Formaggi", 
        description: "Pizza con quattro formaggi diversi", 
        ingredients: ["Mozzarella", "Gorgonzola", "Parmigiano", "Fontina"], 
        image: "quattro_formaggi.jpg", 
        category: "Pizze", 
        price: 7.00 
    },
    {   id: 4, 
        name: "Capricciosa", 
        description: "Pizza con prosciutto, funghi e carciofi", 
        ingredients: ["Pomodoro", "Mozzarella", "Prosciutto", "Funghi", "Carciofi"], 
        image: "capricciosa.jpg", 
        category: "Pizze", 
        price: 7.50 
    },
    {   id: 5, 
        name: "Vegetariana", 
        description: "Pizza con verdure miste", 
        ingredients: ["Pomodoro", "Mozzarella", "Peperoni", "Zucchine", "Melanzane"], 
        image: "vegetariana.jpg", 
        category: "Pizze", 
        price: 6.50 
    },
    {   id: 6, 
        name: "Prosciutto e Funghi", 
        description: "Pizza con prosciutto cotto e funghi", 
        ingredients: ["Pomodoro", "Mozzarella", "Prosciutto cotto", "Funghi"], 
        image: "prosciutto_funghi.jpg", 
        category: "Pizze", 
        price: 7.00 
    },
    {   id: 7, 
        name: "Tonno e Cipolle", 
        description: "Pizza con tonno e cipolle rosse", 
        ingredients: ["Pomodoro", "Mozzarella", "Tonno", "Cipolle rosse"], 
        image: "tonno_cipolle.jpg", 
        category: "Pizze", 
        price: 7.50 
    },
    {   id: 8, 
        name: "Bufalina", 
        description: "Pizza con mozzarella di bufala", 
        ingredients: ["Pomodoro", "Mozzarella di bufala", "Basilico"], 
        image: "bufalina.jpg", 
        category: "Pizze", 
        price: 8.00 
    },
    {   id: 9, 
        name: "Salsiccia e Friarielli", 
        description: "Pizza con salsiccia e friarielli", 
        ingredients: ["Mozzarella", "Salsiccia", "Friarielli"], 
        image: "salsiccia_friarielli.jpg", 
        category: "Pizze", 
        price: 7.50 
    },
    {   id: 10, 
        name: "Frutti di Mare", 
        description: "Pizza con frutti di mare freschi", 
        ingredients: ["Pomodoro", "Mozzarella", "Frutti di mare", "Prezzemolo"], 
        image: "frutti_mare.jpg", 
        category: "Pizze", 
        price: 9.00 
    },
    {   id: 11, 
        name: "Pizza al Pesto", 
        description: "Pizza con pesto di basilico", 
        ingredients: ["Pesto", "Mozzarella", "Pomodorini"], 
        image: "pizza_pesto.jpg", 
        category: "Pizze", 
        price: 7.00 
    },
    {   id: 12, 
        name: "Pizza Tartufata", 
        description: "Pizza con crema di tartufo", 
        ingredients: ["Mozzarella", "Crema di tartufo", "Funghi"], 
        image: "pizza_tartufo.jpg", 
        category: "Pizze", 
        price: 9.50 
    },
],  
    // Panini
    panini: [
    {   id: 13, 
        name: "Panino Classico", 
        description: "Panino con prosciutto e formaggio", 
        ingredients: ["Pane", "Prosciutto cotto", "Formaggio"], 
        image: "panino_classico.jpg", 
        category: "Panini", 
        price: 4.50 
    },
    {   id: 14, 
        name: "Panino con Salsiccia", 
        description: "Panino con salsiccia e verdure", 
        ingredients: ["Pane", "Salsiccia", "Verdure grigliate"], 
        image: "panino_salsiccia.jpg", 
        category: "Panini", 
        price: 5.50 
    },
    {   id: 15, 
        name: "Panino Caprese", 
        description: "Panino con mozzarella e pomodoro", 
        ingredients: ["Pane", "Mozzarella", "Pomodoro", "Basilico"], 
        image: "panino_caprese.jpg", 
        category: "Panini", 
        price: 5.00 
    },
    {   id: 16, 
        name: "Hamburger Classico", 
        description: "Hamburger con carne di manzo e formaggio", 
        ingredients: ["Pane", "Manzo", "Formaggio", "Insalata", "Pomodoro"], 
        image: "hamburger_classico.jpg", 
        category: "Panini", 
        price: 6.50 
    },
    {   id: 17, 
        name: "Hamburger Bacon", 
        description: "Hamburger con carne, bacon e formaggio", 
        ingredients: ["Pane", "Manzo", "Bacon", "Formaggio"], 
        image: "hamburger_bacon.jpg", 
        category: "Panini", 
        price: 7.00 
    },
    {   id: 18, 
        name: "Panino Vegano", 
        description: "Panino con burger vegano e verdure", 
        ingredients: ["Pane", "Burger vegano", "Verdure"], 
        image: "panino_vegano.jpg", 
        category: "Panini", 
        price: 6.00 
    },
    {   id: 19, 
        name: "Panino con Tonno", 
        description: "Panino con tonno e maionese", 
        ingredients: ["Pane", "Tonno", "Maionese", "Pomodoro"], 
        image: "panino_tonno.jpg", 
        category: "Panini", 
        price: 5.50 
    },
    {   id: 20, 
        name: "Panino con Pollo", 
        description: "Panino con pollo grigliato e insalata", 
        ingredients: ["Pane", "Pollo", "Insalata", "Maionese"], 
        image: "panino_pollo.jpg", 
        category: "Panini", 
        price: 6.50 
    },
    {   id: 21, 
        name: "Panino con Speck e Brie", 
        description: "Panino con speck e brie fuso", 
        ingredients: ["Pane", "Speck", "Brie"], 
        image: "panino_speck_brie.jpg", 
        category: "Panini", 
        price: 7.00 
    },
    {   id: 22, 
        name: "Panino con Tacchino", 
        description: "Panino con tacchino e insalata", 
        ingredients: ["Pane", "Tacchino", "Insalata", "Pomodoro"], 
        image: "panino_tacchino.jpg", 
        category: "Panini", 
        price: 6.00 
    },
    {   id: 23, 
        name: "Panino con Porchetta", 
        description: "Panino con porchetta e salsa verde", 
        ingredients: ["Pane", "Porchetta", "Salsa verde"], 
        image: "panino_porchetta.jpg", 
        category: "Panini", 
        price: 7.50 
    },
    {   id: 24, 
        name: "Panino con Zucchine e Melanzane", 
        description: "Panino con verdure grigliate", 
        ingredients: ["Pane", "Zucchine", "Melanzane", "Pesto"], 
        image: "panino_zucchine_melanzane.jpg", 
        category: "Panini", 
        price: 5.50 
    },
],
    // Sushi
    sushi: [
    {   id: 25, 
        name: "Sushi Nigiri", 
        description: "Nigiri con salmone fresco", 
        ingredients: ["Riso", "Salmone"], 
        image: "sushi_nigiri.jpg", 
        category: "Sushi", 
        price: 4.00 
    },
    {   id: 26, 
        name: "Sushi Maki", 
        description: "Maki con tonno e avocado", 
        ingredients: ["Riso", "Tonno", "Avocado"], 
        image: "sushi_maki.jpg", 
        category: "Sushi", 
        price: 5.00 
    },
    {   id: 27, 
        name: "Sashimi", 
        description: "Sashimi di tonno fresco", 
        ingredients: ["Tonno fresco"], 
        image: "sashimi.jpg", 
        category: "Sushi", 
        price: 6.00 
    },
    {   id: 28, 
        name: "Uramaki", 
        description: "Uramaki con gamberi e avocado", 
        ingredients: ["Riso", "Gamberi", "Avocado"], 
        image: "uramaki.jpg", 
        category: "Sushi", 
        price: 6.50 
    },
    {   id: 29, 
        name: "Temaki", 
        description: "Cono di sushi con tonno", 
        ingredients: ["Alga", "Riso", "Tonno", "Avocado"], 
        image: "temaki.jpg", 
        category: "Sushi", 
        price: 5.50 
    },
    {   id: 30, 
        name: "California Roll", 
        description: "Uramaki con surimi e avocado", 
        ingredients: ["Riso", "Surimi", "Avocado", "Cetriolo"], 
        image: "california_roll.jpg", 
        category: "Sushi", 
        price: 6.50 
    },
    {   id: 31, 
        name: "Hosomaki", 
        description: "Hosomaki con cetriolo", 
        ingredients: ["Riso", "Cetriolo"], 
        image: "hosomaki.jpg", 
        category: "Sushi", 
        price: 4.00 
    },
    {   id: 32, 
        name: "Ebi Nigiri", 
        description: "Nigiri con gamberi", 
        ingredients: ["Riso", "Gamberi"], 
        image: "ebi_nigiri.jpg", 
        category: "Sushi", 
        price: 5.00 
    },
    {   id: 33, 
        name: "Dragon Roll", 
        description: "Uramaki con anguilla e avocado", 
        ingredients: ["Riso", "Anguilla", "Avocado"], 
        image: "dragon_roll.jpg", 
        category: "Sushi", 
        price: 7.50 
    },
    {   id: 34, 
        name: "Spicy Tuna Roll", 
        description: "Maki piccante con tonno", 
        ingredients: ["Riso", "Tonno piccante", "Avocado"], 
        image: "spicy_tuna_roll.jpg", 
        category: "Sushi", 
        price: 6.00 
    },
    {   id: 35, 
        name: "Rainbow Roll", 
        description: "Uramaki con vari tipi di pesce", 
        ingredients: ["Riso", "Salmone", "Tonno", "Avocado"], 
        image: "rainbow_roll.jpg", 
        category: "Sushi", 
        price: 7.50 
    },
    {   id: 36, 
        name: "Tuna Tataki", 
        description: "Tonno scottato con salsa ponzu", 
        ingredients: ["Tonno", "Salsa ponzu"], 
        image: "tuna_tataki.jpg", 
        category: "Sushi", 
        price: 8.00 
    },
],
    // Frittura
    fritti: [
    {   id: 37, 
        name: "Patatine Fritte", 
        description: "Classiche patatine fritte croccanti", 
        ingredients: ["Patate", "Olio"], 
        image: "patatine_fritte.jpg", 
        category: "Frittura", 
        price: 3.00 
    },
    {   id: 38, 
        name: "Crocchette di Patate", 
        description: "Crocchette fritte di patate", 
        ingredients: ["Patate", "Pangrattato", "Formaggio"], 
        image: "crocchette_patate.jpg", 
        category: "Frittura", 
        price: 4.00 
    },
    {   id: 39, 
        name: "Anelli di Cipolla", 
        description: "Anelli di cipolla fritti e croccanti", 
        ingredients: ["Cipolla", "Farina", "Olio"], 
        image: "anelli_cipolla.jpg", 
        category: "Frittura", 
        price: 4.50 
    },
    {   id: 40, 
        name: "Mozzarelline Fritte", 
        description: "Bocconcini di mozzarella fritti", 
        ingredients: ["Mozzarella", "Pangrattato", "Olio"], 
        image: "mozzarelline_fritte.jpg", 
        category: "Frittura", 
        price: 4.50 
    },
    {   id: 41, 
        name: "Arancini", 
        description: "Sfere di riso fritte ripiene", 
        ingredients: ["Riso", "Ragù", "Mozzarella"], 
        image: "arancini.jpg", 
        category: "Frittura", 
        price: 5.00 
    },
    {   id: 42, 
        name: "Olive Ascolane", 
        description: "Olive ripiene di carne e fritte", 
        ingredients: ["Olive", "Carne", "Pangrattato"], 
        image: "olive_ascolane.jpg", 
        category: "Frittura", 
        price: 4.50 
    },
    {   id: 43, 
        name: "Supplì", 
        description: "Crocchetta di riso con mozzarella", 
        ingredients: ["Riso", "Mozzarella", "Pomodoro"], 
        image: "suppli.jpg", 
        category: "Frittura", 
        price: 4.00 
    },
    {   id: 44, 
        name: "Calamari Fritti", 
        description: "Anelli di calamari fritti", 
        ingredients: ["Calamari", "Farina", "Olio"], 
        image: "calamari_fritti.jpg", 
        category: "Frittura", 
        price: 7.00 
    },
    {   id: 45, 
        name: "Gamberi Fritti", 
        description: "Gamberi fritti croccanti", 
        ingredients: ["Gamberi", "Farina", "Olio"], 
        image: "gamberi_fritti.jpg", 
        category: "Frittura", 
        price: 7.50 
    },
    {   id: 46, 
        name: "Frittelle di Verdure", 
        description: "Frittelle croccanti di verdure miste", 
        ingredients: ["Zucchine", "Carote", "Farina"], 
        image: "frittelle_verdure.jpg", 
        category: "Frittura", 
        price: 4.00 
    },
    {   id: 47, 
        name: "Panelle", 
        description: "Frittelle di farina di ceci", 
        ingredients: ["Farina di ceci", "Acqua", "Sale"], 
        image: "panelle.jpg", 
        category: "Frittura", 
        price: 3.50 
    },
    {   id: 48, 
        name: "Churros Salati", 
        description: "Churros fritti salati", 
        ingredients: ["Farina", "Olio", "Sale"], 
        image: "churros_salati.jpg", 
        category: "Frittura", 
        price: 5.00 
    },
],
    // Dolci
    dolci: [
    {   id: 49, 
        name: "Tiramisù", 
        description: "Dolce con mascarpone e caffè", 
        ingredients: ["Mascarpone", "Caffè", "Savoiardi"], 
        image: "tiramisu.jpg", 
        category: "Dolci", 
        price: 4.50 
    },
    {   id: 50, 
        name: "Panna Cotta", 
        description: "Dolce al cucchiaio con panna", 
        ingredients: ["Panna", "Zucchero", "Vaniglia"], 
        image: "panna_cotta.jpg", 
        category: "Dolci", 
        price: 4.00 
    },
    {   id: 51, 
        name: "Cheesecake", 
        description: "Torta al formaggio con base croccante", 
        ingredients: ["Formaggio fresco", "Biscotti", "Zucchero"], 
        image: "cheesecake.jpg", 
        category: "Dolci", 
        price: 5.00 
    },
    {   id: 52, 
        name: "Cannoli Siciliani", 
        description: "Dolci ripieni di ricotta", 
        ingredients: ["Ricotta", "Cannolo", "Zucchero"], 
        image: "cannoli_siciliani.jpg", 
        category: "Dolci", 
        price: 5.50 
    },
    {   id: 53, 
        name: "Torta al Cioccolato", 
        description: "Torta soffice al cioccolato", 
        ingredients: ["Cioccolato", "Farina", "Uova"], 
        image: "torta_cioccolato.jpg", 
        category: "Dolci", 
        price: 4.50 
    },
    {   id: 54, 
        name: "Profiteroles", 
        description: "Bignè ripieni di crema e ricoperti di cioccolato", 
        ingredients: ["Bignè", "Crema", "Cioccolato"], 
        image: "profiteroles.jpg", 
        category: "Dolci", 
        price: 6.00 
    },
    {   id: 55, 
        name: "Sfogliatella", 
        description: "Dolce napoletano ripieno di ricotta", 
        ingredients: ["Pasta sfoglia", "Ricotta", "Zucchero"], 
        image: "sfogliatella.jpg", 
        category: "Dolci", 
        price: 3.50 
    },
    {   id: 56, 
        name: "Gelato Artigianale", 
        description: "Gelato artigianale ai gusti vari", 
        ingredients: ["Latte", "Zucchero", "Gusti vari"], 
        image: "gelato_artigianale.jpg", 
        category: "Dolci", 
        price: 4.00 
    },
    {   id: 57, 
        name: "Mousse al Cioccolato", 
        description: "Mousse soffice al cioccolato fondente", 
        ingredients: ["Cioccolato", "Panna", "Zucchero"], 
        image: "mousse_cioccolato.jpg", 
        category: "Dolci", 
        price: 5.00 
    },
    {   id: 58, 
        name: "Crostata di Frutta", 
        description: "Crostata con crema pasticcera e frutta fresca", 
        ingredients: ["Pasta frolla", "Crema pasticcera", "Frutta fresca"], 
        image: "crostata_frutta.jpg", 
        category: "Dolci", 
        price: 4.50 
    },
    {   id: 59, 
        name: "Zeppole", 
        description: "Dolci fritti ripieni di crema", 
        ingredients: ["Farina", "Crema", "Olio"], 
        image: "zeppole.jpg", 
        category: "Dolci", 
        price: 3.00 
    },
    {   id: 60, 
        name: "Crema Catalana", 
        description: "Dolce al cucchiaio con crosta di zucchero caramellato", 
        ingredients: ["Latte", "Zucchero", "Uova"], 
        image: "crema_catalana.jpg", 
        category: "Dolci", 
        price: 5.00 
    },
],
    // Insalate
    insalate: [
    {   id: 61, 
        name: "Insalata Greca", 
        description: "Insalata con feta, pomodori e olive", 
        ingredients: ["Feta", "Pomodori", "Olive", "Cetrioli"], 
        image: "insalata_greca.jpg", 
        category: "Insalate", 
        price: 6.50 
    },
    {   id: 62, 
        name: "Caesar Salad", 
        description: "Insalata con pollo grigliato e crostini", 
        ingredients: ["Insalata", "Pollo grigliato", "Parmigiano", "Crostini"], 
        image: "caesar_salad.jpg", 
        category: "Insalate", 
        price: 7.00 
    },
    {   id: 63, 
        name: "Insalata Caprese", 
        description: "Insalata con mozzarella di bufala e pomodori", 
        ingredients: ["Mozzarella di bufala", "Pomodori", "Basilico"], 
        image: "insalata_caprese.jpg", 
        category: "Insalate", 
        price: 5.50 
    },
    {   id: 64, 
        name: "Insalata di Tonno", 
        description: "Insalata con tonno, uova e fagiolini", 
        ingredients: ["Insalata", "Tonno", "Uova", "Fagiolini"], 
        image: "insalata_tonno.jpg", 
        category: "Insalate", 
        price: 6.50 
    },
    {   id: 65, 
        name: "Insalata di Quinoa", 
        description: "Insalata con quinoa e verdure fresche", 
        ingredients: ["Quinoa", "Cetrioli", "Pomodori", "Avocado"], 
        image: "insalata_quinoa.jpg", 
        category: "Insalate", 
        price: 7.50 
    },
    {   id: 66, 
        name: "Insalata Mista", 
        description: "Insalata con verdure miste di stagione", 
        ingredients: ["Insalata", "Pomodori", "Carote", "Cetrioli"], 
        image: "insalata_mista.jpg", 
        category: "Insalate", 
        price: 5.00 
    },
    {   id: 67, 
        name: "Insalata di Riso", 
        description: "Insalata di riso con verdure e tonno", 
        ingredients: ["Riso", "Tonno", "Verdure", "Olive"], 
        image: "insalata_riso.jpg", 
        category: "Insalate", 
        price: 6.00 
    },
    {   id: 68, 
        name: "Insalata di Pollo", 
        description: "Insalata con pollo, avocado e pomodori", 
        ingredients: ["Insalata", "Pollo", "Avocado", "Pomodori"], 
        image: "insalata_pollo.jpg", 
        category: "Insalate", 
        price: 6.50 
    },
    {   id: 69, 
        name: "Insalata Waldorf", 
        description: "Insalata con mele, noci e sedano", 
        ingredients: ["Mele", "Noci", "Sedano", "Insalata"], 
        image: "insalata_waldorf.jpg", 
        category: "Insalate", 
        price: 7.50 
    },
    {   id: 70, 
        name: "Insalata di Couscous", 
        description: "Insalata di couscous con verdure fresche", 
        ingredients: ["Couscous", "Cetrioli", "Pomodori", "Menta"], 
        image: "insalata_couscous.jpg", 
        category: "Insalate", 
        price: 7.00 
    },
    {   id: 71, 
        name: "Insalata di Mare", 
        description: "Insalata con frutti di mare freschi", 
        ingredients: ["Calamari", "Gamberi", "Polpo", "Prezzemolo"], 
        image: "insalata_mare.jpg", 
        category: "Insalate", 
        price: 9.50 
    },
    {   id: 72, 
        name: "Insalata di Ceci", 
        description: "Insalata con ceci e verdure", 
        ingredients: ["Ceci", "Pomodori", "Cipolla rossa", "Prezzemolo"], 
        image: "insalata_ceci.jpg", 
        category: "Insalate", 
        price: 6.00 
    },
],
    // Bevande
    bevande: [
    {   id: 73, 
        name: "Coca Cola", 
        description: "Bevanda gassata classica", 
        ingredients: ["Acqua", "Zucchero", "An  idr   ide carbonica"], 
        image: "coca_cola.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 74, 
        name: "Acqua Naturale", 
        description: "Acqua minerale naturale", 
        ingredients: ["Acqua"], 
        image: "acqua_naturale.jpg", 
        category: "Bevande", 
        price: 1.50 
    },
    {   id: 75, 
        name: "Acqua Frizzante", 
        description: "Acqua minerale frizzante", 
        ingredients: ["Acqua", "An  idr   ide carbonica"], 
        image: "acqua_frizzante.jpg", 
        category: "Bevande", 
        price: 1.50 
    },
    {   id: 76, 
        name: "Fanta", 
        description: "Bevanda gassata all'arancia", 
        ingredients: ["Acqua", "Zucchero", "Succo d'arancia"], 
        image: "fanta.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 77, 
        name: "Sprite", 
        description: "Bevanda gassata al limone e lime", 
        ingredients: ["Acqua", "Zucchero", "An  idr   ide carbonica", "Limone"], 
        image: "sprite.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 78, 
        name: "Birra", 
        description: "Birra chiara", 
        ingredients: ["Acqua", "Malto d'orzo", "Luppolo"], 
        image: "birra.jpg", 
        category: "Bevande", 
        price: 4.00 
    },
    {   id: 79, 
        name: "Vino Rosso", 
        description: "Bicchiere di vino rosso", 
        ingredients: ["Uva", "Alcol"], 
        image: "vino_rosso.jpg", 
        category: "Bevande", 
        price: 5.00 
    },
    {   id: 80, 
        name: "Vino Bianco", 
        description: "Bicchiere di vino bianco", 
        ingredients: ["Uva", "Alcol"], 
        image: "vino_bianco.jpg", 
        category: "Bevande", 
        price: 5.00 
    },
    {   id: 81, 
        name: "Succo di Frutta", 
        description: "Succo di frutta al gusto pesca", 
        ingredients: ["Pesca", "Acqua", "Zucchero"], 
        image: "succo_frutta.jpg", 
        category: "Bevande", 
        price: 2.00 
    },
    {   id: 82, 
        name: "Limonata", 
        description: "Bevanda fresca al limone", 
        ingredients: ["Acqua", "Zucchero", "Limone"], 
        image: "limonata.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 83, 
        name: "Tè Freddo", 
        description: "Bevanda al tè freddo", 
        ingredients: ["Acqua", "Zucchero", "Tè"], 
        image: "te_freddo.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 84, 
        name: "Caffè", 
        description: "Caffè espresso", 
        ingredients: ["Caffè", "Acqua"], 
        image: "caffe.jpg", 
        category: "Bevande", 
        price: 1.50 
    },
],
};
  