import classic from './assets/Panini/classic.png';
import double from './assets/Panini/double.png';
import avocadoChicken from './assets/Panini/avocado-chicken.png';
import spicySriracha from './assets/Panini/spicy-sriracha.png';
import pulledPork from './assets/Panini/pulled-pork.png';
import mashroom from './assets/Panini/mashroom.png';
import vegan from './assets/Panini/vegan.png';
import fish from './assets/Panini/fish.png';
import lamb from './assets/Panini/lamb.png';
import buffaloChicken from './assets/Panini/buffalo-chicken.png';
import turkey from './assets/Panini/turkey.png';
import halloumi from './assets/Panini/halloumi.png';


export const products = {
    // Pizze
    pizze: [
    {   id: 1, 
        name: "Margherita", 
        description: "Pizza classica con pomodoro e mozzarella", 
        ingredients: ["Pomodoro", "Mozzarella", "Basilico"], 
        image: "margherita.jpg", 
        category: "Pizze", 
        price: 5.00 
    },
    {   id: 2, 
        name: "Diavola", 
        description: "Pizza con salame piccante", 
        ingredients: ["Pomodoro", "Mozzarella", "Salame piccante"], 
        image: "diavola.jpg", 
        category: "Pizze", 
        price: 6.50 
    },
    {   id: 3, 
        name: "Quattro Formaggi", 
        description: "Pizza con quattro formaggi diversi", 
        ingredients: ["Mozzarella", "Gorgonzola", "Parmigiano", "Fontina"], 
        image: "quattro_formaggi.jpg", 
        category: "Pizze", 
        price: 7.00 
    },
    {   id: 4, 
        name: "Capricciosa", 
        description: "Pizza con prosciutto, funghi e carciofi", 
        ingredients: ["Pomodoro", "Mozzarella", "Prosciutto", "Funghi", "Carciofi"], 
        image: "capricciosa.jpg", 
        category: "Pizze", 
        price: 7.50 
    },
    {   id: 5, 
        name: "Vegetariana", 
        description: "Pizza con verdure miste", 
        ingredients: ["Pomodoro", "Mozzarella", "Peperoni", "Zucchine", "Melanzane"], 
        image: "vegetariana.jpg", 
        category: "Pizze", 
        price: 6.50 
    },
    {   id: 6, 
        name: "Prosciutto e Funghi", 
        description: "Pizza con prosciutto cotto e funghi", 
        ingredients: ["Pomodoro", "Mozzarella", "Prosciutto cotto", "Funghi"], 
        image: "prosciutto_funghi.jpg", 
        category: "Pizze", 
        price: 7.00 
    },
    {   id: 7, 
        name: "Tonno e Cipolle", 
        description: "Pizza con tonno e cipolle rosse", 
        ingredients: ["Pomodoro", "Mozzarella", "Tonno", "Cipolle rosse"], 
        image: "tonno_cipolle.jpg", 
        category: "Pizze", 
        price: 7.50 
    },
    {   id: 8, 
        name: "Bufalina", 
        description: "Pizza con mozzarella di bufala", 
        ingredients: ["Pomodoro", "Mozzarella di bufala", "Basilico"], 
        image: "bufalina.jpg", 
        category: "Pizze", 
        price: 8.00 
    },
    {   id: 9, 
        name: "Salsiccia e Friarielli", 
        description: "Pizza con salsiccia e friarielli", 
        ingredients: ["Mozzarella", "Salsiccia", "Friarielli"], 
        image: "salsiccia_friarielli.jpg", 
        category: "Pizze", 
        price: 7.50 
    },
    {   id: 10, 
        name: "Frutti di Mare", 
        description: "Pizza con frutti di mare freschi", 
        ingredients: ["Pomodoro", "Mozzarella", "Frutti di mare", "Prezzemolo"], 
        image: "frutti_mare.jpg", 
        category: "Pizze", 
        price: 9.00 
    },
    {   id: 11, 
        name: "Pizza al Pesto", 
        description: "Pizza con pesto di basilico", 
        ingredients: ["Pesto", "Mozzarella", "Pomodorini"], 
        image: "pizza_pesto.jpg", 
        category: "Pizze", 
        price: 7.00 
    },
    {   id: 12, 
        name: "Pizza Tartufata", 
        description: "Pizza con crema di tartufo", 
        ingredients: ["Mozzarella", "Crema di tartufo", "Funghi"], 
        image: "pizza_tartufo.jpg", 
        category: "Pizze", 
        price: 9.50 
    },
],  
    // Panini
    panini: [
    {
        id: 13,
        name: "Burger Classico di Manzo",
        description: "Un burger tradizionale di manzo con ingredienti freschi e un sapore saporito.",
        ingredients: ["Hamburger di Manzo", "Lattuga", "Pomodoro", "Cheddar", "Cetriolini", "Ketchup", "Panino al Sesamo"],
        image: classic,
        category: "Manzo",
        price: 8.99
        },
        {
        id: 14,
        name: "Double Bacon Cheeseburger",
        description: "Un burger abbondante con due hamburger di manzo, bacon e cheddar fuso.",
        ingredients: ["Doppio Hamburger di Manzo", "Bacon", "Cheddar", "Maionese", "Salsa BBQ", "Cetroli", "Cipolla"],
        image: double,
        category: "Manzo",
        price: 12.99
        },
        {
        id: 15,
        name: "Burger di Pollo e Avocado",
        description: "Un burger di pollo alla griglia sano e delizioso con cremoso avocado.",
        ingredients: ["Pollo fritto", "Avocado", "Cavolo rosso", "Pomodoro", "Cheddar"],
        image: avocadoChicken,
        category: "Chicken",
        price: 9.49
        },
        {
        id: 16,
        name:  "Burger Piccante al Sriracha",
        description: "Un burger di manzo audace e piccante con jalapeños e salsa sriracha per un gusto deciso.",
        ingredients: ["Hamburger di Manzo", "Bacon", "Jalapeños", "Lattuga", "Salsa Sriracha", "Cipolla", "Formaggio svizzero", "Pomodoro"],
        image: spicySriracha,
        category: "Manzo",
        price: 10.49
        },
        {
        id: 17,
        name: "Burger con Maiale Sfilacciato BBQ",
        description: "Un gustoso burger di maiale sfilacciato al BBQ con coleslaw agrodolce.",
        ingredients: ["Maiale Sfilacciato", "Cipolla", "Salsa BBQ", "Cavolo rosso", "Lattuga"],
        image: pulledPork,
        category: "Maiale",
        price: 10.99
        },
        {
        id: 18,
        name: "Burger ai Funghi e Svizzero",
        description: "Un succulento burger di manzo con funghi saltati e formaggio svizzero fuso.",
        ingredients: ["Hamburger di Manzo", "Formaggio svizzero", "Funghi Saltati", "Lattuga", "Maionese all'Aglio"],
        image: mashroom,
        category: "Manzo",
        price: 9.99
        },
        {
        id: 19,
        name: "Burger Vegano ai Fagioli Neri",
        description: "Un delizioso e nutriente burger ai fagioli neri servito con avocado fresco e maionese vegana.",
        ingredients: ["Hamburger di Fagioli Neri", "Avocado", "Lattuga", "Pomodoro", "Cipolla Rossa", "Maionese Vegana"],
        image: vegan,
        category: "Vegano",
        price: 8.49
        },
        {
        id: 20,
        name: "Burger con Filetto di Pesce",
        description: "Un burger di filetto di pesce impanato servito con lattuga e salsa tartara",
        ingredients: ["Filetto di Pesce Impanato", "Lattuga", "Salsa Tartara"],
        image: fish,
        category: "Pesce",
        price: 8.99
        },
        {
        id: 21,
        name: "Burger di Agnello",
        description: "Un burger di agnello con feta, lattuga, pomodoro, cetriolo e salsa tzatziki.",
        ingredients: ["Hamburger di Agnello", "Rucola",
        "Cipolla rossa", "Salsa Tzatziki"],
        image: lamb,
        category: "Agnello",
        price: 11.99
        },
        {
        id: 22,
        name: "Burger di Pollo Buffalo",
        description: "Un croccante burger di pollo fritto con salsa Buffalo, lattuga e formaggio blue.",
        ingredients: ["Pollo Fritto", "Salsa Buffalo", "Lattuga", "Cetriolini",],
        image: buffaloChicken,
        category: "Pollo",
        price: 9.99
        },
        {
        id: 23,
        name: "Burger di Tacchino e Mirtilli",
        description: "Un burger di tacchino servito con salsa di mirtilli rossi e brie, per un tocco autunnale.",
        ingredients: ["Hamburger di Tacchino", "Rucola", "Formaggio fuso", "Salsa di Mirtilli Rossi",],
        image: turkey,
        category: "Tacchino",
        price: 9.49
        },
        {
        id: 24,
        name: "Burger Veggie con Halloumi",
        description: "Un burger vegetariano con halloumi grigliato, zucchine e peperoni rossi, accompagnato da pesto.",
        ingredients: ["Halloumi Grigliato", "Zucchine", "Cetrioli", "Rucola"],
        image: halloumi,
        category: "Vegetariano",
        price: 9.99
        }
],
    // Sushi
    sushi: [
    {   id: 25, 
        name: "Sushi Nigiri Misto", 
        description: "Nigiri con salmone, Tonno, Gambero e Pesce Bianco", 
        ingredients: ["Riso", "Salmone"], 
        image: "sushi_nigiri.jpg", 
        category: "Sushi", 
        price: 12.00 
    },
    {   id: 26, 
        name: "Sushi Maki Misto", 
        description: "Maki con tonno e avocado", 
        ingredients: ["Riso", "Tonno", "Avocado"], 
        image: "sushi_maki.jpg", 
        category: "Sushi", 
        price: 14.00 
    },
    {   id: 27, 
        name: "Sashimi Misto", 
        description: "Sashimi di tonno fresco", 
        ingredients: ["Tonno fresco"], 
        image: "sashimi.jpg", 
        category: "Sushi", 
        price: 18.00 
    },
    {   id: 28, 
        name: "Uramaki", 
        description: "Uramaki con gamberi e avocado", 
        ingredients: ["Riso", "Gamberi", "Avocado"], 
        image: "uramaki.jpg", 
        category: "Sushi", 
        price: 6.50 
    },
    {   id: 29, 
        name: "Temaki", 
        description: "Cono di sushi con salmone", 
        ingredients: ["Alga", "Riso", "Salmone", "Avocado"], 
        image: "temaki.jpg", 
        category: "Sushi", 
        price: 5.50 
    },
    {   id: 30, 
        name: "California Roll", 
        description: "Uramaki con surimi e avocado", 
        ingredients: ["Riso", "Surimi", "Avocado", "Cetriolo"], 
        image: "california_roll.jpg", 
        category: "Sushi", 
        price: 6.50 
    },
    {   id: 31, 
        name: "Hosomaki", 
        description: "Hosomaki con cetriolo", 
        ingredients: ["Riso", "Cetriolo"], 
        image: "hosomaki.jpg", 
        category: "Sushi", 
        price: 4.00 
    },
    {   id: 32, 
        name: "Ebi Nigiri", 
        description: "Nigiri con gamberi", 
        ingredients: ["Riso", "Gamberi"], 
        image: "ebi_nigiri.jpg", 
        category: "Sushi", 
        price: 5.00 
    },
    {   id: 33, 
        name: "Dragon Roll", 
        description: "Uramaki con anguilla e avocado", 
        ingredients: ["Riso", "Anguilla", "Avocado"], 
        image: "dragon_roll.jpg", 
        category: "Sushi", 
        price: 7.50 
    },
    {   id: 34, 
        name: "Spicy Tuna Roll", 
        description: "Maki piccante con tonno", 
        ingredients: ["Riso", "Tonno piccante", "Avocado"], 
        image: "spicy_tuna_roll.jpg", 
        category: "Sushi", 
        price: 6.00 
    },
    {   id: 35, 
        name: "Rainbow Roll", 
        description: "Uramaki con vari tipi di pesce", 
        ingredients: ["Riso", "Salmone", "Tonno", "Avocado"], 
        image: "rainbow_roll.jpg", 
        category: "Sushi", 
        price: 7.50 
    },
    {   id: 36, 
        name: "Tuna Tataki", 
        description: "Tonno scottato con salsa ponzu", 
        ingredients: ["Tonno", "Salsa ponzu"], 
        image: "tuna_tataki.jpg", 
        category: "Sushi", 
        price: 8.00 
    },
],
    // Frittura
    fritti: [
    {   id: 37, 
        name: "Patatine Fritte", 
        description: "Classiche patatine fritte croccanti", 
        ingredients: ["Patate", "Olio"], 
        image: "patatine_fritte.jpg", 
        category: "Frittura", 
        price: 3.00 
    },
    {   id: 38, 
        name: "Crocchette di Patate", 
        description: "Crocchette fritte di patate", 
        ingredients: ["Patate", "Pangrattato", "Formaggio"], 
        image: "crocchette_patate.jpg", 
        category: "Frittura", 
        price: 4.00 
    },
    {   id: 39, 
        name: "Anelli di Cipolla", 
        description: "Anelli di cipolla fritti e croccanti", 
        ingredients: ["Cipolla", "Farina", "Olio"], 
        image: "anelli_cipolla.jpg", 
        category: "Frittura", 
        price: 4.50 
    },
    {   id: 40, 
        name: "Mozzarelline Fritte", 
        description: "Bocconcini di mozzarella fritti", 
        ingredients: ["Mozzarella", "Pangrattato", "Olio"], 
        image: "mozzarelline_fritte.jpg", 
        category: "Frittura", 
        price: 4.50 
    },
    {   id: 41, 
        name: "Arancini", 
        description: "Sfere di riso fritte ripiene", 
        ingredients: ["Riso", "Ragù", "Mozzarella"], 
        image: "arancini.jpg", 
        category: "Frittura", 
        price: 5.00 
    },
    {   id: 42, 
        name: "Olive Ascolane", 
        description: "Olive ripiene di carne e fritte", 
        ingredients: ["Olive", "Carne", "Pangrattato"], 
        image: "olive_ascolane.jpg", 
        category: "Frittura", 
        price: 4.50 
    },
    {   id: 43, 
        name: "Supplì", 
        description: "Crocchetta di riso con mozzarella", 
        ingredients: ["Riso", "Mozzarella", "Pomodoro"], 
        image: "suppli.jpg", 
        category: "Frittura", 
        price: 4.00 
    },
    {   id: 44, 
        name: "Calamari Fritti", 
        description: "Anelli di calamari fritti", 
        ingredients: ["Calamari", "Farina", "Olio"], 
        image: "calamari_fritti.jpg", 
        category: "Frittura", 
        price: 7.00 
    },
    {   id: 45, 
        name: "Gamberi Fritti", 
        description: "Gamberi fritti croccanti", 
        ingredients: ["Gamberi", "Farina", "Olio"], 
        image: "gamberi_fritti.jpg", 
        category: "Frittura", 
        price: 7.50 
    },
    {   id: 46, 
        name: "Frittelle di Verdure", 
        description: "Frittelle croccanti di verdure miste", 
        ingredients: ["Zucchine", "Carote", "Farina"], 
        image: "frittelle_verdure.jpg", 
        category: "Frittura", 
        price: 4.00 
    },
    {   id: 47, 
        name: "Panelle", 
        description: "Frittelle di farina di ceci", 
        ingredients: ["Farina di ceci", "Acqua", "Sale"], 
        image: "panelle.jpg", 
        category: "Frittura", 
        price: 3.50 
    },
    {   id: 48, 
        name: "Churros Salati", 
        description: "Churros fritti salati", 
        ingredients: ["Farina", "Olio", "Sale"], 
        image: "churros_salati.jpg", 
        category: "Frittura", 
        price: 5.00 
    },
],
    // Dolci
    dolci: [
    {   id: 49, 
        name: "Tiramisù", 
        description: "Dolce con mascarpone e caffè", 
        ingredients: ["Mascarpone", "Caffè", "Savoiardi"], 
        image: "tiramisu.jpg", 
        category: "Dolci", 
        price: 4.50 
    },
    {   id: 50, 
        name: "Panna Cotta", 
        description: "Dolce al cucchiaio con panna", 
        ingredients: ["Panna", "Zucchero", "Vaniglia"], 
        image: "panna_cotta.jpg", 
        category: "Dolci", 
        price: 4.00 
    },
    {   id: 51, 
        name: "Cheesecake", 
        description: "Torta al formaggio con base croccante", 
        ingredients: ["Formaggio fresco", "Biscotti", "Zucchero"], 
        image: "cheesecake.jpg", 
        category: "Dolci", 
        price: 5.00 
    },
    {   id: 52, 
        name: "Cannoli Siciliani", 
        description: "Dolci ripieni di ricotta", 
        ingredients: ["Ricotta", "Cannolo", "Zucchero"], 
        image: "cannoli_siciliani.jpg", 
        category: "Dolci", 
        price: 5.50 
    },
    {   id: 53, 
        name: "Torta al Cioccolato", 
        description: "Torta soffice al cioccolato", 
        ingredients: ["Cioccolato", "Farina", "Uova"], 
        image: "torta_cioccolato.jpg", 
        category: "Dolci", 
        price: 4.50 
    },
    {   id: 54, 
        name: "Profiteroles", 
        description: "Bignè ripieni di crema e ricoperti di cioccolato", 
        ingredients: ["Bignè", "Crema", "Cioccolato"], 
        image: "profiteroles.jpg", 
        category: "Dolci", 
        price: 6.00 
    },
    {   id: 55, 
        name: "Sfogliatella", 
        description: "Dolce napoletano ripieno di ricotta", 
        ingredients: ["Pasta sfoglia", "Ricotta", "Zucchero"], 
        image: "sfogliatella.jpg", 
        category: "Dolci", 
        price: 3.50 
    },
    {   id: 56, 
        name: "Gelato Artigianale", 
        description: "Gelato artigianale ai gusti vari", 
        ingredients: ["Latte", "Zucchero", "Gusti vari"], 
        image: "gelato_artigianale.jpg", 
        category: "Dolci", 
        price: 4.00 
    },
    {   id: 57, 
        name: "Mousse al Cioccolato", 
        description: "Mousse soffice al cioccolato fondente", 
        ingredients: ["Cioccolato", "Panna", "Zucchero"], 
        image: "mousse_cioccolato.jpg", 
        category: "Dolci", 
        price: 5.00 
    },
    {   id: 58, 
        name: "Crostata di Frutta", 
        description: "Crostata con crema pasticcera e frutta fresca", 
        ingredients: ["Pasta frolla", "Crema pasticcera", "Frutta fresca"], 
        image: "crostata_frutta.jpg", 
        category: "Dolci", 
        price: 4.50 
    },
    {   id: 59, 
        name: "Zeppole", 
        description: "Dolci fritti ripieni di crema", 
        ingredients: ["Farina", "Crema", "Olio"], 
        image: "zeppole.jpg", 
        category: "Dolci", 
        price: 3.00 
    },
    {   id: 60, 
        name: "Crema Catalana", 
        description: "Dolce al cucchiaio con crosta di zucchero caramellato", 
        ingredients: ["Latte", "Zucchero", "Uova"], 
        image: "crema_catalana.jpg", 
        category: "Dolci", 
        price: 5.00 
    },
],
    // Insalate
    insalate: [
    {   id: 61, 
        name: "Insalata Greca", 
        description: "Insalata con feta, pomodori e olive", 
        ingredients: ["Feta", "Pomodori", "Olive", "Cetrioli"], 
        image: "insalata_greca.jpg", 
        category: "Insalate", 
        price: 6.50 
    },
    {   id: 62, 
        name: "Caesar Salad", 
        description: "Insalata con pollo grigliato e crostini", 
        ingredients: ["Insalata", "Pollo grigliato", "Parmigiano", "Crostini"], 
        image: "caesar_salad.jpg", 
        category: "Insalate", 
        price: 7.00 
    },
    {   id: 63, 
        name: "Insalata Caprese", 
        description: "Insalata con mozzarella di bufala e pomodori", 
        ingredients: ["Mozzarella di bufala", "Pomodori", "Basilico"], 
        image: "insalata_caprese.jpg", 
        category: "Insalate", 
        price: 5.50 
    },
    {   id: 64, 
        name: "Insalata di Tonno", 
        description: "Insalata con tonno, uova e fagiolini", 
        ingredients: ["Insalata", "Tonno", "Uova", "Fagiolini"], 
        image: "insalata_tonno.jpg", 
        category: "Insalate", 
        price: 6.50 
    },
    {   id: 65, 
        name: "Insalata di Quinoa", 
        description: "Insalata con quinoa e verdure fresche", 
        ingredients: ["Quinoa", "Cetrioli", "Pomodori", "Avocado"], 
        image: "insalata_quinoa.jpg", 
        category: "Insalate", 
        price: 7.50 
    },
    {   id: 66, 
        name: "Insalata Mista", 
        description: "Insalata con verdure miste di stagione", 
        ingredients: ["Insalata", "Pomodori", "Carote", "Cetrioli"], 
        image: "insalata_mista.jpg", 
        category: "Insalate", 
        price: 5.00 
    },
    {   id: 67, 
        name: "Insalata di Riso", 
        description: "Insalata di riso con verdure e tonno", 
        ingredients: ["Riso", "Tonno", "Verdure", "Olive"], 
        image: "insalata_riso.jpg", 
        category: "Insalate", 
        price: 6.00 
    },
    {   id: 68, 
        name: "Insalata di Pollo", 
        description: "Insalata con pollo, avocado e pomodori", 
        ingredients: ["Insalata", "Pollo", "Avocado", "Pomodori"], 
        image: "insalata_pollo.jpg", 
        category: "Insalate", 
        price: 6.50 
    },
    {   id: 69, 
        name: "Insalata Waldorf", 
        description: "Insalata con mele, noci e sedano", 
        ingredients: ["Mele", "Noci", "Sedano", "Insalata"], 
        image: "insalata_waldorf.jpg", 
        category: "Insalate", 
        price: 7.50 
    },
    {   id: 70, 
        name: "Insalata di Couscous", 
        description: "Insalata di couscous con verdure fresche", 
        ingredients: ["Couscous", "Cetrioli", "Pomodori", "Menta"], 
        image: "insalata_couscous.jpg", 
        category: "Insalate", 
        price: 7.00 
    },
    {   id: 71, 
        name: "Insalata di Mare", 
        description: "Insalata con frutti di mare freschi", 
        ingredients: ["Calamari", "Gamberi", "Polpo", "Prezzemolo"], 
        image: "insalata_mare.jpg", 
        category: "Insalate", 
        price: 9.50 
    },
    {   id: 72, 
        name: "Insalata di Ceci", 
        description: "Insalata con ceci e verdure", 
        ingredients: ["Ceci", "Pomodori", "Cipolla rossa", "Prezzemolo"], 
        image: "insalata_ceci.jpg", 
        category: "Insalate", 
        price: 6.00 
    },
],
    // Bevande
    bevande: [
    {   id: 73, 
        name: "Coca Cola", 
        description: "Bevanda gassata classica", 
        ingredients: ["Acqua", "Zucchero", "An  idr   ide carbonica"], 
        image: "coca_cola.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 74, 
        name: "Acqua Naturale", 
        description: "Acqua minerale naturale", 
        ingredients: ["Acqua"], 
        image: "acqua_naturale.jpg", 
        category: "Bevande", 
        price: 1.50 
    },
    {   id: 75, 
        name: "Acqua Frizzante", 
        description: "Acqua minerale frizzante", 
        ingredients: ["Acqua", "An  idr   ide carbonica"], 
        image: "acqua_frizzante.jpg", 
        category: "Bevande", 
        price: 1.50 
    },
    {   id: 76, 
        name: "Fanta", 
        description: "Bevanda gassata all'arancia", 
        ingredients: ["Acqua", "Zucchero", "Succo d'arancia"], 
        image: "fanta.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 77, 
        name: "Sprite", 
        description: "Bevanda gassata al limone e lime", 
        ingredients: ["Acqua", "Zucchero", "An  idr   ide carbonica", "Limone"], 
        image: "sprite.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 78, 
        name: "Birra", 
        description: "Birra chiara", 
        ingredients: ["Acqua", "Malto d'orzo", "Luppolo"], 
        image: "birra.jpg", 
        category: "Bevande", 
        price: 4.00 
    },
    {   id: 79, 
        name: "Vino Rosso", 
        description: "Bicchiere di vino rosso", 
        ingredients: ["Uva", "Alcol"], 
        image: "vino_rosso.jpg", 
        category: "Bevande", 
        price: 5.00 
    },
    {   id: 80, 
        name: "Vino Bianco", 
        description: "Bicchiere di vino bianco", 
        ingredients: ["Uva", "Alcol"], 
        image: "vino_bianco.jpg", 
        category: "Bevande", 
        price: 5.00 
    },
    {   id: 81, 
        name: "Succo di Frutta", 
        description: "Succo di frutta al gusto pesca", 
        ingredients: ["Pesca", "Acqua", "Zucchero"], 
        image: "succo_frutta.jpg", 
        category: "Bevande", 
        price: 2.00 
    },
    {   id: 82, 
        name: "Limonata", 
        description: "Bevanda fresca al limone", 
        ingredients: ["Acqua", "Zucchero", "Limone"], 
        image: "limonata.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 83, 
        name: "Tè Freddo", 
        description: "Bevanda al tè freddo", 
        ingredients: ["Acqua", "Zucchero", "Tè"], 
        image: "te_freddo.jpg", 
        category: "Bevande", 
        price: 2.50 
    },
    {   id: 84, 
        name: "Caffè", 
        description: "Caffè espresso", 
        ingredients: ["Caffè", "Acqua"], 
        image: "caffe.jpg", 
        category: "Bevande", 
        price: 1.50 
    },
],
};
  